### ISSUE TITLE
Need coco-pretrained weights

### ISSUE THREAD

**Issue by tricoffee** [VDIGPKU/CBNet_pytorch#7]
Would you mind sharing your pretrained model weights for us ?

**Comment by lddsjy** [comment]
> Would you mind sharing your pretrained model weights for us ?

Hi. Have you got that?

**Comment by tricoffee** [comment]
I have got that. But I can not train **Dual-ResNeXt152** with the pretrained model weights _db-x101-32-4d.pth_. I train this model in the way of distributed training by using mmdetection dist_train.sh script. My device configs are i7 cpu with 64 G，two 2080ti GPUs. However in the process of training, it encountered **OOM** errors. I think it need more gpu memory to make a model copy.
I train **Dual-ResNeXt152** from scratch, no bug, but the model doesn't converge.



`    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/runner.py", line 384, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/runner.py", line 290, in train
    self.call_hook('after_train_iter')
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/runner.py", line 245, in call_hook
    getattr(hook, fn_name)(self)
  File "/code/CBNet/mmdet/core/utils/dist_utils.py", line 53, in after_train_iter
    runner.outputs['loss'].backward()
  File "/opt/conda/lib/python3.6/site-packages/torch/tensor.py", line 150, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 66.00 MiB (GPU 0; 10.76 GiB total capacity; 8.51 GiB already allocated; 62.19 MiB free; 1.35 GiB cached)
`

**Comment by lddsjy** [comment]
> I have got that. But I can not train Dual-ResNeXt152 with the pretrained model weights db-x101-32-4d.pth. I train this model in the way of distributed training by using mmdetection dist_train.sh script. My device configs are i7 cpu with 64 G，two 2080ti GPUs. However in the process of training, it encountered OOM errors. I think it need more gpu memory to make a model copy.
> I train Dual-ResNeXt152 from scratch, no bug, but the model doesn't converge.
>    runner.run(data_loaders, cfg.workflow, cfg.total_epochs) File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/runner.py", line 384, in run epoch_runner(data_loaders[i], **kwargs) File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/runner.py", line 290, in train self.call_hook('after_train_iter') File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/runner.py", line 245, in call_hook getattr(hook, fn_name)(self) File "/code/CBNet/mmdet/core/utils/dist_utils.py", line 53, in after_train_iter runner.outputs['loss'].backward() File "/opt/conda/lib/python3.6/site-packages/torch/tensor.py", line 150, in backward torch.autograd.backward(self, gradient, retain_graph, create_graph) File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward allow_unreachable=True)  # allow_unreachable flag RuntimeError: CUDA out of memory. Tried to allocate 66.00 MiB (GPU 0; 10.76 GiB total capacity; 8.51 GiB already allocated; 62.19 MiB free; 1.35 GiB cached)

Maybe you can try a smaller batchsize and remember to reduce learning rate correspondently

**Comment by kartikJ-9** [comment]
Where do you get the .pth file ?

**Comment by kartikJ-9** [comment]
> > I have got that. But I can not train Dual-ResNeXt152 with the pretrained model weights db-x101-32-4d.pth. I train this model in the way of distributed training by using mmdetection dist_train.sh script. My device configs are i7 cpu with 64 G，two 2080ti GPUs. However in the process of training, it encountered OOM errors. I think it need more gpu memory to make a model copy.
> > I train Dual-ResNeXt152 from scratch, no bug, but the model doesn't converge.
> > runner.run(data_loaders, cfg.workflow, cfg.total_epochs) File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/runner.py", line 384, in run epoch_runner(data_loaders[i], **kwargs) File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/runner.py", line 290, in train self.call_hook('after_train_iter') File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/runner.py", line 245, in call_hook getattr(hook, fn_name)(self) File "/code/CBNet/mmdet/core/utils/dist_utils.py", line 53, in after_train_iter runner.outputs['loss'].backward() File "/opt/conda/lib/python3.6/site-packages/torch/tensor.py", line 150, in backward torch.autograd.backward(self, gradient, retain_graph, create_graph) File "/opt/conda/lib/python3.6/site-packages/torch/autograd/**init**.py", line 99, in backward allow_unreachable=True)  # allow_unreachable flag RuntimeError: CUDA out of memory. Tried to allocate 66.00 MiB (GPU 0; 10.76 GiB total capacity; 8.51 GiB already allocated; 62.19 MiB free; 1.35 GiB cached)
> 
> Maybe you can try a smaller batchsize and remember to reduce learning rate correspondently

How to reduce batchsize? How do I get rid of this CUDA out of memory

**Comment by chenzyhust** [comment]
> Would you mind sharing your pretrained model weights for us ?

can you share the pretrained model weights db-x101-32-4d.pth to my emil:624851287@qq.com.Thank you very much!

**Comment by tricoffee** [comment]
> > Would you mind sharing your pretrained model weights for us ?
> 
> can you share the pretrained model weights db-x101-32-4d.pth to my emil:[624851287@qq.com.Thank](mailto:624851287@qq.com.Thank) you very much!

You can download the pretrained model weights file from https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/resnext101_32x4d-a5af3160.pth, then run this python script https://github.com/VDIGPKU/CBNet/blob/master/convert_db.py to get _'db-x101-32-4d.pth'_
